import { Data_base } from "./data_base.mjs";
import { Logic } from "./logic.mjs";
import { Interface } from "./interface_node.mjs";
// import { read_file } from "./read_file.mjs";
const dbs = new Data_base();
const log = new Logic(dbs);
const intre = new Interface(log);
// dbs.read_file();
// read_file();
await dbs.read_file_item();
await dbs.read_file_delivery();
// await dbs.read_file_delivery_parcel();
await dbs.read_file_not_delivery();
intre.run();